# RDS Postgres module — reusable across envs.
#
# Layout:
#   - DB subnet group spanning provided private subnets
#   - Security group allowing 5432 from the VPC CIDR
#   - Single Postgres instance, encrypted at rest with the account default KMS key
#   - Master password generated by terraform, stored in Secrets Manager
#   - CNAME `pg.<env>.meandr.internal` → instance endpoint (so connection strings
#     are stable across replacements)
#
# What this module deliberately does NOT do:
#   - Per-service DB users / GRANTs — Rails handles its own user via migrations
#   - Cross-region replicas — production HA strategy is TBD (logical replication
#     vs. read replicas); single instance is sufficient for staging
#   - Password rotation — Secrets Manager supports it; we'll wire the rotation
#     Lambda when we're ready to test it end-to-end

# --- Master password -----------------------------------------------------

resource "random_password" "master" {
  length  = 32
  special = true
  # RDS disallows `/`, `@`, `"`, ` `. We also drop `!` and `#` (shell-quoting
  # surprises in connection strings even though RDS itself allows them).
  override_special = "_-=+"
}

resource "aws_secretsmanager_secret" "master" {
  name        = var.secret_name
  description = "RDS master password for ${var.name}. Rotated by Secrets Manager (when wired). Read by meandr-api task role only."

  tags = merge(var.tags, {
    Name = "${var.name} master password"
  })
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    engine   = "postgres"
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = var.db_name

    # Pre-assembled connection URL — apps can inject this directly via
    # ECS task `secrets` instead of composing from parts.
    #
    # The RDS ENDPOINT, not a CNAME. `verify-full` checks the hostname
    # against the certificate and RDS issues only for the endpoint name,
    # so an alias can never validate — which is why the alias is gone
    # rather than merely unused. The cost is that recreating the instance
    # changes this URL and tasks must restart to see it; the endpoint
    # survives reboots and Multi-AZ failover, so that only happens during
    # a deliberate replacement, which is disruptive regardless.
    #
    # No sslrootcert here: the RDS roots are a private Amazon PKI, so the
    # trust store is a property of the CLIENT image. Each app points at
    # its own vendored copy via PGSSLROOTCERT.
    url = "postgres://${var.master_username}:${urlencode(random_password.master.result)}@${aws_db_instance.main.address}:${aws_db_instance.main.port}/${var.db_name}?sslmode=verify-full"
  })
}

# --- Networking ----------------------------------------------------------

resource "aws_db_subnet_group" "main" {
  name       = var.name
  subnet_ids = var.private_subnet_ids

  tags = merge(var.tags, {
    Name = "${var.name} subnets"
  })
}

resource "aws_security_group" "main" {
  name        = "${var.name}-rds"
  description = "Postgres access for ${var.name}"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, {
    Name = "${var.name} RDS SG"
  })
}

resource "aws_security_group_rule" "ingress_vpc" {
  type              = "ingress"
  security_group_id = aws_security_group.main.id

  from_port   = 5432
  to_port     = 5432
  protocol    = "tcp"
  cidr_blocks = [var.vpc_cidr_block]
  description = "Postgres from within VPC"
}

# Egress: RDS doesn't initiate outbound connections in normal operation, but AWS
# requires SGs to have explicit egress rules. Leave allow-all — there's no
# real surface here.
resource "aws_security_group_rule" "egress_all" {
  type              = "egress"
  security_group_id = aws_security_group.main.id

  from_port   = 0
  to_port     = 0
  protocol    = "-1"
  cidr_blocks = ["0.0.0.0/0"]
  description = "Allow all outbound"
}

locals {
  # Changing any of these requires a reboot. Postgres reads them once at
  # startup; RDS queues them as pending-reboot rather than erroring.
  static_parameters = ["max_connections", "shared_buffers", "max_worker_processes"]
}

# --- Parameters ----------------------------------------------------------
#
# The RDS defaults are formulas over DBInstanceClassMemory with FLOORS that
# were written for larger machines, and on a 1 GiB instance the floors win:
# autovacuum_work_mem resolves to its 64 MiB minimum rather than the 32 MiB
# the formula wants, times a 3-worker minimum, so autovacuum alone can hold
# ~19% of RAM. Add 25% for shared_buffers and the instance is committed
# before a client connects.
#
# max_connections matters for a second reason. Its default resolves to a
# number the machine cannot honour, so demand is bounded by the OOM killer
# instead of by Postgres. A refused connection is a Rails exception; an OOM
# is a crash-recovery outage. Bounding it here makes the failure legible.
resource "aws_db_parameter_group" "main" {
  name_prefix = "${var.name}-"
  family      = "postgres${split(".", var.engine_version)[0]}"
  description = "Tuned for ${var.instance_class}. ASCII only: RDS rejects non-printable and non-ASCII characters here, mid-apply."

  dynamic "parameter" {
    for_each = var.db_parameters
    content {
      name  = parameter.key
      value = parameter.value

      # Static parameters need a reboot; declaring them "immediate" makes
      # the apply fail rather than queue.
      apply_method = contains(local.static_parameters, parameter.key) ? "pending-reboot" : "immediate"
    }
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = var.tags
}

# --- Instance ------------------------------------------------------------

resource "aws_db_instance" "main" {
  identifier = var.name

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  parameter_group_name = aws_db_parameter_group.main.name

  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb > 0 ? var.max_allocated_storage_gb : null
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.main.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  backup_retention_period = var.backup_retention_days
  backup_window           = "03:00-04:00" # UTC; off-peak for EU traffic
  maintenance_window      = "Mon:04:00-Mon:05:00"

  auto_minor_version_upgrade = true
  apply_immediately          = true

  performance_insights_enabled          = true
  performance_insights_retention_period = 7 # free tier

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-final-${formatdate("YYYYMMDD-hhmm", timestamp())}"
  copy_tags_to_snapshot     = true

  tags = merge(var.tags, {
    Name = "${var.name} DB"
  })

  lifecycle {
    # The final_snapshot_identifier uses timestamp() which churns every plan.
    # Ignore it — only matters at destroy time anyway.
    ignore_changes = [final_snapshot_identifier, password]
  }
}

# No internal CNAME for Postgres, deliberately.
#
# An alias cannot satisfy `verify-full` — RDS issues its certificate for
# the endpoint name, so connecting through `pg.<env>.meandr.internal`
# fails hostname verification no matter what is in the trust store.
# Keeping the record would only invite someone to use it and quietly land
# back on a weaker sslmode.
