# RDS Postgres module — reusable across envs.
#
# Layout:
#   - DB subnet group spanning provided private subnets
#   - Security group allowing 5432 from the VPC CIDR
#   - Single Postgres instance, encrypted at rest with the account default KMS key
#   - Master password generated by terraform, stored in Secrets Manager
#   - CNAME `pg.<env>.meandr.local` → instance endpoint (so connection strings
#     are stable across replacements)
#
# What this module deliberately does NOT do:
#   - Per-service DB users / GRANTs — Rails handles its own user via migrations
#   - Cross-region replicas — production HA strategy is TBD (logical replication
#     vs. read replicas); single instance is sufficient for staging
#   - Password rotation — Secrets Manager supports it; we'll wire the rotation
#     Lambda when we're ready to test it end-to-end

# --- Master password -----------------------------------------------------

resource "random_password" "master" {
  length  = 32
  special = true
  # RDS disallows `/`, `@`, `"`, ` `. We also drop `!` and `#` (shell-quoting
  # surprises in connection strings even though RDS itself allows them).
  override_special = "_-=+"
}

resource "aws_secretsmanager_secret" "master" {
  name        = var.secret_name
  description = "RDS master password for ${var.name}. Rotated by Secrets Manager (when wired). Read by meandr-api task role only."

  tags = merge(var.tags, {
    Name = "${var.name} master password"
  })
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    engine   = "postgres"
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = var.db_name
  })
}

# --- Networking ----------------------------------------------------------

resource "aws_db_subnet_group" "main" {
  name       = var.name
  subnet_ids = var.private_subnet_ids

  tags = merge(var.tags, {
    Name = "${var.name} subnets"
  })
}

resource "aws_security_group" "main" {
  name        = "${var.name}-rds"
  description = "Postgres access for ${var.name}"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, {
    Name = "${var.name} RDS SG"
  })
}

resource "aws_security_group_rule" "ingress_vpc" {
  type              = "ingress"
  security_group_id = aws_security_group.main.id

  from_port   = 5432
  to_port     = 5432
  protocol    = "tcp"
  cidr_blocks = [var.vpc_cidr_block]
  description = "Postgres from within VPC"
}

# Egress: RDS doesn't initiate outbound connections in normal operation, but AWS
# requires SGs to have explicit egress rules. Leave allow-all — there's no
# real surface here.
resource "aws_security_group_rule" "egress_all" {
  type              = "egress"
  security_group_id = aws_security_group.main.id

  from_port   = 0
  to_port     = 0
  protocol    = "-1"
  cidr_blocks = ["0.0.0.0/0"]
  description = "Allow all outbound"
}

# --- Instance ------------------------------------------------------------

resource "aws_db_instance" "main" {
  identifier = var.name

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb > 0 ? var.max_allocated_storage_gb : null
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.main.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  backup_retention_period = var.backup_retention_days
  backup_window           = "03:00-04:00"     # UTC; off-peak for EU traffic
  maintenance_window      = "Mon:04:00-Mon:05:00"

  auto_minor_version_upgrade = true
  apply_immediately          = true

  performance_insights_enabled = true
  performance_insights_retention_period = 7  # free tier

  deletion_protection      = var.deletion_protection
  skip_final_snapshot      = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-final-${formatdate("YYYYMMDD-hhmm", timestamp())}"
  copy_tags_to_snapshot    = true

  tags = merge(var.tags, {
    Name = "${var.name} DB"
  })

  lifecycle {
    # The final_snapshot_identifier uses timestamp() which churns every plan.
    # Ignore it — only matters at destroy time anyway.
    ignore_changes = [final_snapshot_identifier, password]
  }
}

# --- Internal DNS --------------------------------------------------------

resource "aws_route53_record" "pg" {
  zone_id = var.internal_dns_zone_id
  name    = "pg.${var.internal_dns_zone_name}"
  type    = "CNAME"
  ttl     = 60
  records = [aws_db_instance.main.address]
}
